apiVersion: v1
kind: Service
metadata:
  name: local-api-service
  labels:
    app: local-api
spec:
  type: NodePort
  ports:
  - targetPort: 8000
    port: 8000
    nodePort: 30080
  selector:
    app: local-api
